<?php

namespace ContainerMDnnXIP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LCkNFCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lCk_nFC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lCk_nFC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\TestController::all' => ['privates', '.service_locator..eHqkeB', 'get_ServiceLocator__EHqkeBService', true],
            'App\\Controller\\TestController::delete' => ['privates', '.service_locator.hs7LkXo', 'get_ServiceLocator_Hs7LkXoService', true],
            'App\\Controller\\TestController::test' => ['privates', '.service_locator..eHqkeB', 'get_ServiceLocator__EHqkeBService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\TestController:all' => ['privates', '.service_locator..eHqkeB', 'get_ServiceLocator__EHqkeBService', true],
            'App\\Controller\\TestController:delete' => ['privates', '.service_locator.hs7LkXo', 'get_ServiceLocator_Hs7LkXoService', true],
            'App\\Controller\\TestController:test' => ['privates', '.service_locator..eHqkeB', 'get_ServiceLocator__EHqkeBService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\TestController::all' => '?',
            'App\\Controller\\TestController::delete' => '?',
            'App\\Controller\\TestController::test' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\TestController:all' => '?',
            'App\\Controller\\TestController:delete' => '?',
            'App\\Controller\\TestController:test' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
