<?php

namespace ContainerNrkUcek;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_JZFq7F7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.JZFq7F7' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/MessageHandler/SampleMessangeHandler.php';

        return $container->privates['.messenger.handler_descriptor.JZFq7F7'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\SampleMessangeHandler(($container->privates['App\\Repository\\MessagesRepository'] ?? $container->load('getMessagesRepositoryService'))), []);
    }
}
