<?php

namespace ContainerQKeNHIf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hs7LkXoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hs7LkXo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hs7LkXo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', '.errored..service_locator.hs7LkXo.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.hs7LkXo": it references class "App\\Entity\\Task" but no such service exists.'],
        ], [
            'id' => 'App\\Entity\\Task',
        ]);
    }
}
