<?php

namespace ContainerCJIj54t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1I_WqGJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1I.WqGJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1I.WqGJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bus' => ['privates', '.errored.AbZ6ocd', NULL, 'Cannot determine controller argument for "App\\Controller\\SampleController::sample()": the $bus argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Messenger\\MessageBusInterface".'],
        ], [
            'bus' => '?',
        ]);
    }
}
