<?php

namespace ContainerCJIj54t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_AbZ6ocdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.AbZ6ocd' shared service.
     *
     * @return \Symfony\Component\Messenger\MessageBusInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\SampleController::sample()": the $bus argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Messenger\\MessageBusInterface".');
    }
}
