<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYj7hi0O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYj7hi0O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYj7hi0O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYj7hi0O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYj7hi0O\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yj7hi0O',
    'container.build_id' => '89ef4dfa',
    'container.build_time' => 1669489335,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYj7hi0O');
