<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZmLLxFW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZmLLxFW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZmLLxFW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZmLLxFW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZmLLxFW\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZmLLxFW',
    'container.build_id' => '20b465c6',
    'container.build_time' => 1669562335,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZmLLxFW');
