<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH05RJ30\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH05RJ30/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH05RJ30.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH05RJ30\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH05RJ30\App_KernelDevDebugContainer([
    'container.build_hash' => 'H05RJ30',
    'container.build_id' => '01d666cd',
    'container.build_time' => 1669576813,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH05RJ30');
