<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'messages' => [[], ['_controller' => 'App\\Controller\\MessagesController::messages'], [], [['text', '/messages']], [], []],
    'get_messages' => [['id', 'toId'], ['_controller' => 'App\\Controller\\MessagesController::getBySenderID'], [], [['variable', '/', '[^/]++', 'toId', true], ['text', '/recipients'], ['variable', '/', '[^/]++', 'id', true], ['text', '/messages']], [], []],
    'test2' => [[], ['_controller' => 'App\\Controller\\MessagesController::test2'], [], [['text', '/test2']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/']], [], []],
    'all' => [[], ['_controller' => 'App\\Controller\\TestController::all'], [], [['text', '/all']], [], []],
    'test' => [[], ['_controller' => 'App\\Controller\\TestController::test'], [], [['text', '/test']], [], []],
    'create-task' => [[], ['_controller' => 'App\\Controller\\TestController::create'], [], [['text', '/create']], [], []],
    'update-status' => [['id'], ['_controller' => 'App\\Controller\\TestController::updateTaskStatus'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/updateStatus']], [], []],
    'delete-task' => [['id'], ['_controller' => 'App\\Controller\\TestController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/deleteTask']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
